olxbr/quality-gate-action

README.md
action.yml
src/github_client.sh
src/report.sh
src/sonarcloud_analysis.sh
src/sonarcloud_client.sh
src/templates/report.md

- Add SonarCloud client
- Add SonarCloud calls and analysis
- Add SonarCloud analysis in results
- Update Readme.md
- Remove unused utils.sh from github client

Feat: SonarCloud Analysis (Coverage and Static Analysis)

---

action.yml
src/github_client.sh
src/unit_test.sh

- Added new endpoint in the github client to check workflows and jobs;
- Added ENVs required for unit test verification;
- Implemented new unit test verification logic;

Feat: new unit test check

---

README.md
action.yml
src/repo_configs.sh
src/report.sh
src/sonarcloud_analysis.sh
src/unit_test.sh
src/utils.sh

- Included the `gates_to_skip` input
- Included function to print `gates_to_skip` values if they exist
- GATES_TO_SKIP validations and logic to skip gates
- Refactoring variable names and logic
- README.md update

Feat: Including Skip Gates

---

src/sonarcloud_analysis.sh
src/unit_test.sh
src/utils.sh

- Create the `_retry_with_delay` function in utils
- Use the `_retry_with_delay` function to call APIs
- Improve logs

Feat: Improve retries and logs

---

src/sonarcloud_analysis.sh

- Get sonar_project_key from prop file if exists
In some cases the name of the repository may change, but the key in SonarCloud remains the old one.

feat: get sonar_project_key from prop file if exists

---

README.md
action.yml
src/github_client.sh
src/repo_configs.sh
src/sonarcloud_analysis.sh
src/sonarcloud_client.sh
src/unit_test.sh
src/utils.sh

Feat
* Get status report from default branch if no data was found on pull request
* Add some debug logs
Refac
* Implements a setup default vars to be used in all steps (Clean)
* Remove set default branch. Using runtime object to extract
* Remove useless code on LOG funcion
Message when status report is from defaul branch

Feat: Get main coverage if data was missing on PR

---

src/sonarcloud_analysis.sh

Get the right message on quality gate.

Fix - Get right message

---

README.md
action.yml
src/sonarcloud_analysis.sh
src/submit_metrics.sh
src/unit_test.sh

Send quality gates metrics to exporter
> * Skipped gates as boolean
> * Metrics and thresold from sonar (Coverage and Static)
> * Pull request size. Numbers of commits, add, del and changes
> * Pull request created at
Sample of data sent to exporter

Feat send skip gates to gh exporter

---

src/report.sh
src/submit_metrics.sh

Feat: 
> Add new metric boolean metric

Feat: Add conclusion status for easy query on DATALAKE

---

src/submit_metrics.sh

Update
> Send data as is to exporter

Update: Using same Schema from Datalake

---

src/repo_configs.sh

Read the json as a big list

---

src/github_client.sh
src/repo_configs.sh
src/report.sh
src/sonarcloud_analysis.sh
src/submit_metrics.sh
src/unit_test.sh
src/utils.sh

- Implement logic to always create new report comment on PR
- Some refactor and lint using shfmt

feat: Always create new report comment

---

src/unit_test.sh

Skip unit-test check if step is not present in workflow directory.
It's better wait 3 seconds then 30/60 minutes
* Sample when step is configured
* Sample when step it NOT configured

Feat: skip wait unit-test when possible

---

.github/pull_request_template.md
src/report.sh

- Fix `vulnerability pass` env in badge checks
- It was always return as `Failed!` checks.

Fix: status badge checks

---

src/submit_metrics.sh

- Add ID's of PR and Repository
- For better match on Joins. Asked by Joao (Prod Ops)

Feat: Add New IDs to quality gates table.

---

action.yml
src/sonarcloud_analysis.sh
src/sonarcloud_client.sh

- Implement coverage analysis based on Overall Code and Estimated After Merge
- Add `_get_coverage_measure` function to SonarCloud Client
- Add `coverage_threshold` as action input
- To check overall code coverage instead of new code and prepare for Gate Lock!

Feat: Change Coverage Analysis to be based on Overall Code(default branch) and Estimated After Merge(pull request)

---

action.yml
src/quality_gates.sh
src/repo_configs.sh
src/report.sh
src/submit_metrics.sh
src/templates/report.md
src/utils.sh

- Implement Quality Gate Lock
-

Feat: Coverage Gate Lock

---

action.yml
src/quality_gates.sh
src/repo_configs.sh
src/report.sh
src/sonarcloud_analysis.sh
src/submit_metrics.sh
src/unit_test.sh

- Using same vars in all step (Correct default values)
- To avoid misunderstand
Before this PR
Correct Values

Refac update default timeouts in 1 place

---

src/submit_metrics.sh

- Set empty structure when null or empty array to fix parquet file generation

Fix(static analysis metrics): Set empty structure when null or empty array

---

src/sonarcloud_analysis.sh

- Send metrics to DataLake without formatting, to facilitate calculations, filters and data ordering

Feat(static analysis): Send Metrics to DataLake Without Formatting

---

src/submit_metrics.sh

- Remove Static Analysis Field If Empty To Be Null In DataLake

Feat(submit metrics): Remove Static Analysis Field If Empty To Be Null In DataLake

---

src/sonarcloud_analysis.sh
src/sonarcloud_client.sh

- Refactor the "check configs" to better understand the code and avoid overriding the warning message value
- Fix the "if" that tests whether the analysis is complete
- When getting coverage measure it returns empty if the value is null

Fix(sonar cloud analysis): Fix Some Bugs Found In Tests

---

src/github_client.sh
src/quality_gates.sh
src/repo_configs.sh

- Remove validation from `Dependabot Security Updates` as it's not mandatory and some teams prefer to do it manually

Feat(dependabot configs): Remove Dependabot Security Update Validation

---

src/quality_gates.sh

- Activate Quality Gate Locks (Unit Test, Code Review and Owner Approval)
- To force projects to comply with Quality Gates

Feat(quality gates): Activating gate locks

---

src/sonarcloud_analysis.sh

- Set `default_branch_coverage_value` to the Pull Request value when it is empty. This is necessary because during the initial execution of the project, the default branch metric is not yet available.
- Adapt the code to validate if the value is below the threshold in cases of equal values
- Some refactors

Feat(sonar cloud analysis): Improve Coverage Checks

---

src/sonarcloud_analysis.sh

- Fix `coverage_status` to "OK" if values are equals
- Some refators

Fix(sonarcloud analysis): Fix coverage_status And Refactor

---

src/github_client.sh
src/quality_gates.sh
src/repo_configs.sh
src/report.sh
src/sonarcloud_analysis.sh
src/sonarcloud_client.sh
src/unit_test.sh
src/utils.sh

- Removes color on each call logs line
- To reuse from log level and keep code more clean

refac(logs): use color set on level instead declare all calls
